const API = "https://playlist-api.bookingelbrayan.workers.dev";
const $ = (s) => document.querySelector(s);
const escapeHtml = (v="") => String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function dateCO(v){const d=new Date(v);return Number.isNaN(d.getTime())?"DURO":new Intl.DateTimeFormat("es-CO",{day:"numeric",month:"short",year:"numeric"}).format(d)}
function href(a){return `/noticias/${encodeURIComponent(a.slug)}`}
function image(a){return a.cover_image||""}
function renderHero(a){const hero=$("#heroSection");if(!a.length){hero.innerHTML=`<div class="hero-main loaded"><div class="hero-copy"><span class="eyebrow">DURO · ENTRETENIMIENTO</span><h1>La cultura urbana tiene una nueva casa.</h1><p>Noticias, música, artistas, historias y tendencias con una perspectiva propia.</p></div></div><div class="hero-side"><a class="hero-card" href="/playlist.html" style="background-image:url('/assets/brayan-portrait.jpeg')"><div class="hero-card-copy"><span class="eyebrow">DESCUBRE</span><h2>Playlist</h2><p>Música, comunidad y directos.</p></div></a><a class="hero-card" href="/quienes-somos.html" style="background-image:url('/assets/brayan-portrait-glasses.jpeg')"><div class="hero-card-copy"><span class="eyebrow">CONOCE DURO</span><h2>La visión</h2><p>El proyecto detrás del medio.</p></div></a></div>`;return}const [main,...side]=a;const bg=image(main)?`background-image:linear-gradient(180deg,rgba(0,0,0,.02) 15%,rgba(0,0,0,.92) 100%),url('${escapeHtml(image(main))}')`:"";hero.innerHTML=`<a class="hero-main loaded" href="${href(main)}" style="${bg}"><div class="hero-copy"><span class="eyebrow">${escapeHtml(main.category||"NOTICIAS")}</span><h1>${escapeHtml(main.title)}</h1><p>${escapeHtml(main.excerpt||"La historia detrás de lo que está pasando.")}</p><div class="hero-meta">${escapeHtml(main.author||"DURO")} · ${dateCO(main.published_at)}</div></div></a><div class="hero-side">${side.slice(0,2).map((x,i)=>`<a class="hero-card" href="${href(x)}" style="${image(x)?`background-image:linear-gradient(180deg,rgba(0,0,0,.02),rgba(0,0,0,.93)),url('${escapeHtml(image(x))}')`:i===0?"background-image:url('/assets/brayan-portrait.jpeg')":"background-image:url('/assets/brayan-portrait-glasses.jpeg')"}"><div class="hero-card-copy"><span class="eyebrow">${escapeHtml(x.category||"NOTICIAS")}</span><h2>${escapeHtml(x.title)}</h2><p>${dateCO(x.published_at)}</p></div></a>`).join("")}</div>`}
function renderNews(a){const grid=$("#newsGrid");if(!a.length){grid.innerHTML='<div class="news-empty">Todavía no hay artículos publicados. La portada se actualizará automáticamente cuando publiques desde el sistema editorial.</div>';return}grid.innerHTML=a.slice(0,6).map(x=>`<article class="news-card"><a class="news-image" href="${href(x)}">${image(x)?`<img src="${escapeHtml(image(x))}" alt="${escapeHtml(x.title)}" loading="lazy" decoding="async">`:""}</a><div class="news-body"><span class="section-kicker">${escapeHtml(x.category||"NOTICIAS")}</span><h3><a href="${href(x)}">${escapeHtml(x.title)}</a></h3><p>${escapeHtml(x.excerpt||"")}</p><div class="news-meta">${escapeHtml(x.author||"DURO")} · ${dateCO(x.published_at)}</div></div></article>`).join("")}
function renderRanking(a){$("#rankingList").innerHTML=a.slice(0,5).map((x,i)=>`<div class="rank-item"><span class="rank-num">${String(i+1).padStart(2,"0")}</span><a href="${href(x)}"><span class="rank-cat">${escapeHtml(x.category||"NOTICIAS")}</span>${escapeHtml(x.title)}</a></div>`).join("")||'<div class="rank-item"><span class="rank-num">—</span><span>La conversación comienza aquí.</span></div>'}
function renderTrends(a){const c=[...new Set(a.map(x=>x.category).filter(Boolean))].slice(0,5);if(c.length)$("#trendItems").innerHTML=c.map(x=>`<span>${escapeHtml(x).toUpperCase()}</span>`).join("")}
async function load(){try{const r=await fetch(`${API}/articles?limit=20`,{cache:"no-store"});if(!r.ok)throw Error(r.status);const d=await r.json();const a=Array.isArray(d.articles)?d.articles:[];renderHero(a);renderNews(a);renderRanking(a);renderTrends(a)}catch(e){console.error("DURO articles",e);renderHero([]);renderNews([]);renderRanking([])}}
function menu(){const b=$("#menuToggle"),n=$("#mobileNav");b?.addEventListener("click",()=>{const o=n.classList.toggle("open");b.setAttribute("aria-expanded",String(o));b.textContent=o?"✕":"☰"})}
function search(){const b=$("#searchToggle"),p=$("#searchPanel"),i=$("#searchInput");b?.addEventListener("click",()=>{p.hidden=!p.hidden;if(!p.hidden)i.focus()});document.addEventListener("keydown",e=>{if(e.key==="Escape")p.hidden=true;if(e.key==="/"&&document.activeElement!==i){e.preventDefault();p.hidden=false;i.focus()}})}
menu();search();load();
